### ISSUE TITLE
Connections for Two-Qubit Gates on Tenerife README.md

### ISSUE THREAD

**Issue by giovanipollachini** [QISKit/qiskit-backend-information#17]
Hello,

There seems to be a mistake on the qubit connections for the CNOT gate on Tenerife README.md . 
(link: https://github.com/QISKit/qiskit-backend-information/tree/master/backends/tenerife/V1 )
I think the correct image would be something like this:
![ibmqx4_tenerife_connections](https://user-images.githubusercontent.com/39380361/40392546-61f2701a-5df2-11e8-8172-29e323cb011a.png)
since I can only do these gates on the composer:
![cnot_gates](https://user-images.githubusercontent.com/39380361/40392545-61ceb6ca-5df2-11e8-8f2e-263cc28f09e3.png)
Is that correct?

Thanks

**Comment by jaygambetta** [comment]
should be fix now as we have pushed all directions to the version log.
